enum ActionTypes {
  GET_SINGLE_DATA = 'BLINKLINK_REACT_TEST/COUNTRY_MANAGEMENT/GET_SINGLE_DATA',
  GET_SINGLE_DATA_SUCCESS = 'BLINKLINK_REACT_TEST/COUNTRY_MANAGEMENT/GET_SINGLE_DATA_SUCCESS',
  GET_SINGLE_DATA_FAILED = 'BLINKLINK_REACT_TEST/COUNTRY_MANAGEMENT/GET_SINGLE_DATA_FAILED'
}

export default ActionTypes;
