enum ActionTypes {
  GET_COUNTRY_DATA = 'BLINKLINK_REACT_TEST/HOME_MANAGEMENT/GET_COUNTRY_DATA',
  GET_COUNTRY_DATA_SUCCESS = 'BLINKLINK_REACT_TEST/HOME_MANAGEMENT/GET_COUNTRY_DATA_SUCCESS',
  GET_COUNTRY_DATA_FAILED = 'BLINKLINK_REACT_TEST/HOME_MANAGEMENT/GET_COUNTRY_DATA_FAILED',

  GET_SEARCH_DATA = 'BLINKLINK_REACT_TEST/HOME_MANAGEMENT/GET_SEARCH_DATA',
  GET_SEARCH_DATA_SUCCESS = 'BLINKLINK_REACT_TEST/HOME_MANAGEMENT/GET_SEARCH_DATA_SUCCESS',
  GET_SEARCH_DATA_FAILED = 'BLINKLINK_REACT_TEST/HOME_MANAGEMENT/GET_SEARCH_DATA_FAILED'
}

export default ActionTypes;
